export type WordCategory = 'noun' | 'verb' | 'adj' | 'adverb' | 'prep';

/** Scene themes words can be weighted for. Phase 4a added 'tavern'; Phase 4b
 * adds 'dungeon' alongside the original Phase 1 'kitchen' theme. */
export type WordTheme = 'kitchen' | 'tavern' | 'dungeon';

export interface WordEntry {
  word: string;
  category: WordCategory;
  /** Per-theme selection weight. A theme with no entry here defaults to 1. */
  themeWeights?: Partial<Record<WordTheme, number>>;
}

/** Single source of truth for every categorized (non-literal) word. */
export const WORD_ENTRIES: WordEntry[] = [
  // --- nouns ---
  { word: 'dog', category: 'noun' },
  { word: 'cat', category: 'noun' },
  { word: 'magic', category: 'noun' },
  { word: 'fridge', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'snack', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'dream', category: 'noun' },
  { word: 'shadow', category: 'noun', themeWeights: { dungeon: 2 } },
  { word: 'light', category: 'noun' },
  { word: 'coffee', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'stars', category: 'noun' },
  { word: 'kitchen', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'ghost', category: 'noun' },
  { word: 'time', category: 'noun' },
  { word: 'machine', category: 'noun' },
  { word: 'moon', category: 'noun' },
  { word: 'sun', category: 'noun' },
  { word: 'rain', category: 'noun' },
  { word: 'storm', category: 'noun' },
  { word: 'ocean', category: 'noun' },
  { word: 'mountain', category: 'noun' },
  { word: 'river', category: 'noun' },
  { word: 'forest', category: 'noun' },
  { word: 'garden', category: 'noun' },
  { word: 'flower', category: 'noun' },
  { word: 'bird', category: 'noun' },
  { word: 'wolf', category: 'noun' },
  { word: 'fox', category: 'noun' },
  { word: 'bear', category: 'noun' },
  { word: 'snow', category: 'noun' },
  { word: 'ice', category: 'noun' },
  { word: 'fire', category: 'noun', themeWeights: { tavern: 2 } },
  { word: 'ash', category: 'noun' },
  { word: 'smoke', category: 'noun' },
  { word: 'silence', category: 'noun' },
  { word: 'noise', category: 'noun' },
  { word: 'song', category: 'noun' },
  { word: 'melody', category: 'noun' },
  { word: 'echo', category: 'noun', themeWeights: { dungeon: 2 } },
  { word: 'mirror', category: 'noun' },
  { word: 'window', category: 'noun' },
  { word: 'door', category: 'noun' },
  { word: 'key', category: 'noun', themeWeights: { dungeon: 2 } },
  { word: 'lock', category: 'noun', themeWeights: { dungeon: 2 } },
  { word: 'letter', category: 'noun' },
  { word: 'secret', category: 'noun', themeWeights: { tavern: 2 } },
  { word: 'memory', category: 'noun' },
  { word: 'heart', category: 'noun' },
  { word: 'soul', category: 'noun' },
  { word: 'spirit', category: 'noun' },
  { word: 'angel', category: 'noun' },
  { word: 'devil', category: 'noun' },
  { word: 'stranger', category: 'noun', themeWeights: { tavern: 2 } },
  { word: 'friend', category: 'noun' },
  { word: 'family', category: 'noun' },
  { word: 'home', category: 'noun' },
  { word: 'road', category: 'noun' },
  { word: 'journey', category: 'noun', themeWeights: { tavern: 2 } },
  { word: 'map', category: 'noun' },
  { word: 'compass', category: 'noun' },
  { word: 'clock', category: 'noun' },
  { word: 'hour', category: 'noun' },
  { word: 'morning', category: 'noun' },
  { word: 'evening', category: 'noun' },
  { word: 'night', category: 'noun' },
  { word: 'winter', category: 'noun' },
  { word: 'summer', category: 'noun' },
  { word: 'spring', category: 'noun' },
  { word: 'autumn', category: 'noun' },
  { word: 'honey', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'sugar', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'salt', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'bread', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'wine', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'tea', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'milk', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'butter', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'apple', category: 'noun', themeWeights: { kitchen: 3 } },
  { word: 'ale', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'quest', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'sword', category: 'noun', themeWeights: { tavern: 3, dungeon: 2 } },
  { word: 'dragon', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'bard', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'tavern', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'mead', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'gold', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'oath', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'blade', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'tankard', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'legend', category: 'noun', themeWeights: { tavern: 3 } },
  { word: 'torch', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'rune', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'skeleton', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'crypt', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'curse', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'treasure', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'abyss', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'chains', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'goblin', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'crumbling', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'stone', category: 'noun', themeWeights: { dungeon: 3 } },
  { word: 'dagger', category: 'noun', themeWeights: { dungeon: 3 } },

  // --- verbs ---
  { word: 'love', category: 'verb' },
  { word: 'hate', category: 'verb' },
  { word: 'sleep', category: 'verb' },
  { word: 'dance', category: 'verb' },
  { word: 'whisper', category: 'verb' },
  { word: 'breathe', category: 'verb' },
  { word: 'sing', category: 'verb' },
  { word: 'run', category: 'verb' },
  { word: 'fly', category: 'verb' },
  { word: 'fall', category: 'verb' },
  { word: 'rise', category: 'verb' },
  { word: 'shine', category: 'verb' },
  { word: 'glow', category: 'verb' },
  { word: 'burn', category: 'verb' },
  { word: 'freeze', category: 'verb' },
  { word: 'melt', category: 'verb' },
  { word: 'break', category: 'verb' },
  { word: 'mend', category: 'verb' },
  { word: 'hold', category: 'verb' },
  { word: 'release', category: 'verb' },
  { word: 'wonder', category: 'verb' },
  { word: 'wander', category: 'verb' },
  { word: 'chase', category: 'verb' },
  { word: 'hide', category: 'verb' },
  { word: 'seek', category: 'verb' },
  { word: 'remember', category: 'verb' },
  { word: 'forget', category: 'verb' },
  { word: 'laugh', category: 'verb' },
  { word: 'cry', category: 'verb' },
  { word: 'smile', category: 'verb' },
  { word: 'frown', category: 'verb' },
  { word: 'kiss', category: 'verb' },
  { word: 'embrace', category: 'verb' },
  { word: 'wait', category: 'verb' },
  { word: 'hope', category: 'verb' },
  { word: 'fear', category: 'verb' },
  { word: 'trust', category: 'verb' },
  { word: 'betray', category: 'verb' },
  { word: 'forgive', category: 'verb' },
  { word: 'listen', category: 'verb' },

  // --- adjectives ---
  { word: 'hot', category: 'adj' },
  { word: 'cold', category: 'adj' },
  { word: 'midnight', category: 'adj', themeWeights: { kitchen: 2 } },
  { word: 'slow', category: 'adj' },
  { word: 'fast', category: 'adj' },
  { word: 'beautiful', category: 'adj' },
  { word: 'broken', category: 'adj' },
  { word: 'quiet', category: 'adj' },
  { word: 'loud', category: 'adj' },
  { word: 'soft', category: 'adj' },
  { word: 'hard', category: 'adj' },
  { word: 'sweet', category: 'adj' },
  { word: 'bitter', category: 'adj' },
  { word: 'sour', category: 'adj' },
  { word: 'warm', category: 'adj' },
  { word: 'cool', category: 'adj' },
  { word: 'bright', category: 'adj' },
  { word: 'dark', category: 'adj' },
  { word: 'pale', category: 'adj' },
  { word: 'golden', category: 'adj' },
  { word: 'silver', category: 'adj' },
  { word: 'silent', category: 'adj' },
  { word: 'wild', category: 'adj' },
  { word: 'gentle', category: 'adj' },
  { word: 'fierce', category: 'adj' },
  { word: 'tender', category: 'adj' },
  { word: 'cruel', category: 'adj' },
  { word: 'kind', category: 'adj' },
  { word: 'strange', category: 'adj' },
  { word: 'familiar', category: 'adj' },
  { word: 'distant', category: 'adj' },
  { word: 'close', category: 'adj' },
  { word: 'empty', category: 'adj' },
  { word: 'full', category: 'adj' },
  { word: 'heavy', category: 'adj' },
  { word: 'ancient', category: 'adj', themeWeights: { tavern: 2, dungeon: 2 } },
  { word: 'young', category: 'adj' },
  { word: 'old', category: 'adj' },
  { word: 'new', category: 'adj' },
  { word: 'lost', category: 'adj' },
  { word: 'found', category: 'adj' },
  { word: 'sacred', category: 'adj' },
  { word: 'forbidden', category: 'adj' },
  { word: 'endless', category: 'adj' },
  { word: 'fleeting', category: 'adj' },
  { word: 'eternal', category: 'adj' },
  { word: 'fragile', category: 'adj' },
  { word: 'brave', category: 'adj' },
  { word: 'curious', category: 'adj' },
  { word: 'restless', category: 'adj' },

  // --- adverbs ---
  { word: 'always', category: 'adverb' },
  { word: 'never', category: 'adverb' },
  { word: 'softly', category: 'adverb' },
  { word: 'quietly', category: 'adverb' },
  { word: 'slowly', category: 'adverb' },
  { word: 'quickly', category: 'adverb' },
  { word: 'gently', category: 'adverb' },
  { word: 'wildly', category: 'adverb' },
  { word: 'sadly', category: 'adverb' },
  { word: 'brightly', category: 'adverb' },
  { word: 'silently', category: 'adverb' },
  { word: 'forever', category: 'adverb' },
  { word: 'again', category: 'adverb' },
  { word: 'still', category: 'adverb' },
  { word: 'almost', category: 'adverb' },
  { word: 'barely', category: 'adverb' },
  { word: 'deeply', category: 'adverb' },
  { word: 'truly', category: 'adverb' },
  { word: 'simply', category: 'adverb' },
  { word: 'suddenly', category: 'adverb' },

  // --- prepositions ---
  { word: 'in', category: 'prep' },
  { word: 'on', category: 'prep' },
  { word: 'with', category: 'prep' },
  { word: 'for', category: 'prep' },
  { word: 'of', category: 'prep' },
  { word: 'under', category: 'prep' },
  { word: 'beside', category: 'prep' },
  { word: 'through', category: 'prep' },
  { word: 'over', category: 'prep' },
  { word: 'before', category: 'prep' },
  { word: 'after', category: 'prep' },
  { word: 'until', category: 'prep' },
  { word: 'near', category: 'prep' },
  { word: 'without', category: 'prep' },
  { word: 'beyond', category: 'prep' },
];

/** Uncategorized function words (articles, pronouns, copulas) used as
 * literal template tokens rather than drawn from a category. */
const LITERALS: string[] = [
  'the', 'a', 'an', 'is', 'and', 'to', 'you', 'I', 'it', 'that',
  'was', 'are', 'as', 'my', 'his', 'her', 'they', 'why', 'we', 'he',
  'she', 'this', 'our', 'its', 'their', 'not',
];

export const WORDS: string[] = [...LITERALS, ...WORD_ENTRIES.map((entry) => entry.word)];

function wordsForCategory(category: WordCategory): string[] {
  return WORD_ENTRIES.filter((entry) => entry.category === category).map((entry) => entry.word);
}

export const CATEGORIES: Record<WordCategory, string[]> = {
  noun: wordsForCategory('noun'),
  verb: wordsForCategory('verb'),
  adj: wordsForCategory('adj'),
  adverb: wordsForCategory('adverb'),
  prep: wordsForCategory('prep'),
};

const WEIGHT_LOOKUP = new Map<string, Partial<Record<WordTheme, number>>>(
  WORD_ENTRIES.filter((entry) => entry.themeWeights).map((entry) => [entry.word, entry.themeWeights!]),
);

/** Selection weight for `word` under `theme`. Defaults to 1 for words with no
 * configured weight for that theme (including uncategorized literals). */
export function getThemeWeight(word: string, theme: WordTheme): number {
  return WEIGHT_LOOKUP.get(word)?.[theme] ?? 1;
}
